version: 0.0.{build}
branches:
  only:
  - master
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  project: OpenARLog.sln
  verbosity: minimal
test: off
deploy: off
